#!/usr/bin/env bash
# Storytime
while IFS=: read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOMEDIR COMMAND
do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIR and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < /etc/passwd
