#!/usr/bin/env bash
# Storytime
while ifs=: read -r username password userID groupID userIDinfo homeDir shell
do
	echo "The user $username is part of the $groupID gang, lives in $homeDir and rides $shell. $userID's place is protected by the passcode $password, more info about the user here: $userIDinfo"
done < /etc/passwd
